#**iNeuron**
## Programming Assignment - 8 (Python Basic)

- Batch - Full Stack Data Science Bootcamp 2.0
- Name - **Mayur Soni**
- Email ID - **mayurssoni007@gmail.com**

------------------------------------------------

#Q1.) Write a Python Program to Add Two Matrices ?

In [27]:
import numpy as np

m1 = [[1,2,3],
      [4,5,6],
      [7,8,9]
      ]
m2 = [[9,8,7],
      [6,5,4],
      [3,2,1]
      ]

print(f"1st Matrix is : {m1}")
print(f"2nd Matrix is : {m2}")

a1 = np.array(m1)
a2 = np.array(m2)

addition = a1 + a2

print("\nAddition of 2 Matrices is : ")
print(addition)

1st Matrix is : [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
2nd Matrix is : [[9, 8, 7], [6, 5, 4], [3, 2, 1]]

Addition of 2 Matrices is : 
[[10 10 10]
 [10 10 10]
 [10 10 10]]


------------------------------------------------

#Q2.) Write a Python Program to Multiply Two Matrices ?

In [26]:
import numpy as np

m1 = [[1,2,3],
      [4,5,6],
      [7,8,9]
      ]
m2 = [[9,8,7],
      [6,5,4],
      [3,2,1]
      ]

print(f"1st Matrix is : {m1}")
print(f"2nd Matrix is : {m2}")

a1 = np.array(m1)
a2 = np.array(m2)

multiplication = a1 * a2

print("\nMultiplication of 2 Matrices is : ")
print(multiplication)

1st Matrix is : [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
2nd Matrix is : [[9, 8, 7], [6, 5, 4], [3, 2, 1]]

Multiplication of 2 Matrices is : 
[[ 9 16 21]
 [24 25 24]
 [21 16  9]]


--------------------------------------------------------

#Q.3) Write a Python Program to Transpose a Matrix ?

In [28]:
import numpy as np

m1 = [[1,2,3],
      [4,5,6],
      [7,8,9]
      ]

print(f"Matrix is : {m1}")

a1 = np.transpose(m1)

print(f"\nTransposed Matrix is : ")
print(a1)

Matrix is : [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

Transposed Matrix is : 
[[1 4 7]
 [2 5 8]
 [3 6 9]]


-----------------------------------------------

#Q.4) Write a Python Program to Sort Words in Alphabetic Order ?

In [30]:
import numpy as np

alpha = ['Mayur','Anand','Yuzvendra','Uttam','Robin']

print(f"Unsorted Words are : {alpha}")

sort = np.sort(alpha)

print("\nSorted Words in Alphabetic Order are : ")
print(sort)

Unsorted Words are : ['Mayur', 'Anand', 'Yuzvendra', 'Uttam', 'Robin']

Sorted Words in Alphabetic Order are : 
['Anand' 'Mayur' 'Robin' 'Uttam' 'Yuzvendra']


----------------------------------------------------------

#Q.5) Write a Python Program to Remove Punctuation From a String ?

In [34]:
test_string = "My@ name: is ! Mayur'; Soni."

print(f"The Original String is : {test_string}")

punc = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''

for ele in test_string:
  if ele in punc:
    test_string = test_string.replace(ele, "")

print(f"\nThe String after Punctuation Removal is : {test_string}")

The Original String is : My@ name: is ! Mayur'; Soni.

The String after Punctuation Removal is : My name is  Mayur Soni


------------------------------------------------------------End------------------------------------------------------------